# Generated by Django 4.2.18 on 2025-03-06 02:51
# 已改为 TextField，不再依赖 GDAL/GeoDjango

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandParcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geometry", models.TextField(blank=True, null=True)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("area", models.FloatField()),
            ],
        ),
    ]
