# Generated by Django 4.2.18 on 2025-03-06 08:37
# 已改为 TextField，不再依赖 GDAL/GeoDjango

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutrientDeficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nutrient_type",
                    models.CharField(
                        choices=[("N", "缺氮"), ("P", "缺磷"), ("K", "缺钾")], max_length=10
                    ),
                ),
                ("deficiency_geometry", models.TextField()),
                (
                    "intensity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app2.landparcel",
                    ),
                ),
            ],
        ),
    ]
