# Generated by Django 4.2.18 on 2025-03-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_nutrientdeficiency"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=16, verbose_name="用户名")),
                ("password", models.CharField(max_length=16, verbose_name="密码")),
                ("phone", models.CharField(max_length=13, verbose_name="电话号")),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="TOKEN",
                    ),
                ),
                ("device_count", models.IntegerField(default=0, verbose_name="设备数")),
                ("field_count", models.IntegerField(default=0, verbose_name="地块数")),
            ],
            options={
                "db_table": "user_tb",
            },
        ),
        migrations.AddField(
            model_name="landparcel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_parcels",
                to="app2.user",
            ),
        ),
    ]
