# Generated by Django 5.0.7 on 2025-03-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0003_user_landparcel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="landparcel",
            name="field_type",
            field=models.SmallIntegerField(
                choices=[(1, "高肥力"), (2, "中肥力"), (3, "低肥力")],
                default=1,
                verbose_name="地块土质类型",
            ),
        ),
    ]
