# Generated by Django 5.0.7 on 2025-03-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0004_landparcel_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landparcel",
            name="field_type",
            field=models.SmallIntegerField(
                choices=[(1, "高肥力"), (2, "中肥力"), (3, "低肥力")],
                default=2,
                verbose_name="地块土质类型",
            ),
        ),
        migrations.CreateModel(
            name="Fer_record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fer_num", models.IntegerField(default=0, verbose_name="施肥记录序号")),
                (
                    "growth_stage",
                    models.SmallIntegerField(
                        choices=[(1, "发芽期"), (2, "生长期"), (3, "开花期"), (4, "结荚期")],
                        verbose_name="生长阶段",
                    ),
                ),
                (
                    "fer_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="施肥时间"),
                ),
                (
                    "N_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="氮肥消耗量",
                    ),
                ),
                (
                    "P_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="磷肥消耗量",
                    ),
                ),
                (
                    "K_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="钾肥消耗量",
                    ),
                ),
                (
                    "S_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="总消耗量",
                    ),
                ),
                (
                    "fer_location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="施肥位置"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "field_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app2.landparcel",
                        verbose_name="地块编号",
                    ),
                ),
            ],
            options={
                "verbose_name": "施肥记录",
                "verbose_name_plural": "施肥记录",
                "db_table": "Fer_detail_tb",
                "indexes": [
                    models.Index(
                        fields=["field_id", "fer_time"],
                        name="Fer_detail__field_i_1a05d6_idx",
                    )
                ],
                "unique_together": {("field_id", "fer_num")},
            },
        ),
    ]
