# Generated by Django 5.0.7 on 2025-03-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0005_alter_landparcel_field_type_fer_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fer_record",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="fer_record",
            name="Fer_detail__field_i_1a05d6_idx",
        ),
        migrations.AlterUniqueTogether(
            name="fer_record",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fer_record",
            name="base_k_used",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="基础钾肥用量"
            ),
        ),
        migrations.AddField(
            model_name="fer_record",
            name="base_n_used",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="基础氮肥用量"
            ),
        ),
        migrations.AddField(
            model_name="fer_record",
            name="base_p_used",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="基础磷肥用量"
            ),
        ),
        migrations.AddField(
            model_name="fer_record",
            name="base_s_used",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="基础总用量"
            ),
        ),
        migrations.AlterModelTable(
            name="fer_record",
            table=None,
        ),
        migrations.RemoveField(
            model_name="fer_record",
            name="K_used",
        ),
        migrations.RemoveField(
            model_name="fer_record",
            name="N_used",
        ),
        migrations.RemoveField(
            model_name="fer_record",
            name="P_used",
        ),
        migrations.RemoveField(
            model_name="fer_record",
            name="S_used",
        ),
    ]
