# Generated by Django 5.0.7 on 2025-03-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0006_alter_fer_record_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fer_record",
            options={"verbose_name": "施肥记录", "verbose_name_plural": "施肥记录"},
        ),
        migrations.AlterUniqueTogether(
            name="fer_record",
            unique_together={("field_id", "fer_num")},
        ),
        migrations.AddIndex(
            model_name="fer_record",
            index=models.Index(
                fields=["field_id", "fer_time"], name="Fer_detail__field_i_1a05d6_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="fer_record",
            table="Fer_detail_tb",
        ),
    ]
