# Generated by Django 4.2.29 on 2026-03-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_remove_gis_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fer_region_record',
            name='fer_geometry',
            field=models.TextField(verbose_name='施肥区域几何信息'),
        ),
        migrations.AlterField(
            model_name='nutrientdeficiency',
            name='deficiency_geometry',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.FloatField()),
                ('total_volume', models.FloatField()),
                ('level', models.FloatField()),
                ('pump_state', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='app2.user')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
            },
        ),
        migrations.CreateModel(
            name='PendingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='pending_images/%Y/%m/%d/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_images', to='app2.landparcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_images', to='app2.user')),
            ],
            options={
                'verbose_name': 'Pending Image',
                'verbose_name_plural': 'Pending Images',
            },
        ),
    ]
