# Generated by Django 4.2.29 on 2026-03-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_alter_fer_record_growth_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_num', models.IntegerField(default=0, verbose_name='记录序号')),
                ('spray_time', models.DateTimeField(auto_now_add=True, verbose_name='施药时间')),
                ('pesticide_name', models.CharField(default='', max_length=128, verbose_name='农药名称')),
                ('dosage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='用量')),
                ('unit', models.CharField(blank=True, default='ml', max_length=32, verbose_name='单位')),
                ('target_pest', models.CharField(blank=True, max_length=128, null=True, verbose_name='防治对象')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.landparcel', verbose_name='地块编号')),
            ],
            options={
                'verbose_name': '农药记录',
                'verbose_name_plural': '农药记录',
                'db_table': 'pesticide_record_tb',
                'indexes': [models.Index(fields=['field_id', 'spray_time'], name='pesticide_r_field_i_129809_idx')],
                'unique_together': {('field_id', 'record_num')},
            },
        ),
    ]
