# Generated by Django 5.0.7 on 2025-03-10 12:37
# 已改为 TextField，不再依赖 GDAL/GeoDjango

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0007_alter_fer_record_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fer_region_record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fer_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="追肥时间"),
                ),
                (
                    "fer_geometry",
                    models.TextField(verbose_name="施肥区域几何信息"),
                ),
                (
                    "extra_n_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="额外氮肥用量",
                    ),
                ),
                (
                    "extra_p_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="额外磷肥用量",
                    ),
                ),
                (
                    "extra_k_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="额外钾肥用量",
                    ),
                ),
                (
                    "deficiencies",
                    models.ManyToManyField(
                        blank=True, to="app2.nutrientdeficiency", verbose_name="关联的缺素区域"
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app2.landparcel",
                        verbose_name="地块编号",
                    ),
                ),
            ],
            options={
                "db_table": "fer_region_record_tb",
            },
        ),
    ]
