# Generated by Django 4.2.29 on 2026-03-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_remove_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landparcel',
            name='area',
            field=models.FloatField(verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='landparcel',
            name='name',
            field=models.CharField(default='未命名地块', max_length=64, verbose_name='地块名称'),
        ),
        migrations.AlterModelTable(
            name='landparcel',
            table='app2_landparcel',
        ),
        migrations.AlterModelTable(
            name='nutrientdeficiency',
            table='app2_nutrientdeficiency',
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('无人机', '无人机'), ('传感器', '传感器'), ('执行器', '执行器')], max_length=32, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('在线', '在线'), ('离线', '离线')], default='在线', max_length=16, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app2.user')),
            ],
            options={
                'db_table': 'app2_device',
            },
        ),
    ]
