# Generated by Django 4.2.29 on 2026-03-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_device_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fer_record',
            name='growth_stage',
            field=models.SmallIntegerField(choices=[(1, '苗期'), (2, '还苗期'), (3, '伸根期'), (4, '旺长期'), (5, '成熟期')], verbose_name='生长阶段'),
        ),
    ]
