# Generated by Django 5.2.17 on 2026-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0018_roles_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='curingbatch',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='harvestbatch',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
