<template>
  <div class="workflow-page"><header class="page-head"><div><span class="eyebrow">烘烤端</span><h1>烘烤批次</h1><p>跟踪烤房、烘烤阶段和现场温湿度。</p></div><button class="primary" type="button" @click="showForm=!showForm">{{ showForm ? '收起表单' : '新建批次' }}</button></header>
    <form v-if="showForm" class="form-panel" @submit.prevent="create"><div class="form-grid"><label>烘烤批次号<input v-model.trim="form.batch_no" placeholder="如 2026-C-001" required></label><label>采收批次<select v-model="form.harvest_batch_id" required><option value="">请选择采收批次</option><option v-for="b in harvests" :key="b.id" :value="b.id">{{ b.batch_no }} · {{ b.fresh_weight }} kg</option></select></label><label>烤房<input v-model.trim="form.barn_name" placeholder="如 1 号烤房" required></label><label>当前阶段<select v-model="form.stage"><option value="yellowing">变黄</option><option value="color_fixing">定色</option><option value="stem_drying">干筋</option></select></label><label>温度（℃）<input v-model="form.temperature" type="number" step="0.1"></label><label>湿度（%）<input v-model="form.humidity" type="number" min="0" max="100" step="0.1"></label></div><div class="form-actions"><button class="primary" :disabled="busy || !harvests.length">{{ busy ? '保存中…' : '保存批次' }}</button><button class="secondary" type="button" @click="showForm=false">取消</button></div><p v-if="message" class="message" role="status">{{ message }}</p><p v-if="!harvests.length" class="form-hint">暂无可关联的采收批次，请先完成采收记录。</p></form>
    <section class="table-panel"><div class="panel-title"><strong>烘烤记录</strong><span>{{ items.length }} 条</span></div><div v-if="loading" class="empty">正在加载批次…</div><div v-else-if="loadError" class="empty error"><p>{{ loadError }}</p><button class="secondary" @click="load">重试</button></div><div v-else-if="!items.length" class="empty">暂无烘烤批次。关联采收批次后即可记录烤房作业。</div><div v-for="item in items" v-else :key="item.id" class="batch-row"><div class="batch-main"><strong>{{ item.batch_no }}</strong><span v-if="item.is_demo" class="demo-tag">演示样例</span><small>{{ item.barn_name }} · {{ stageText[item.stage] || item.stage }} · {{ item.temperature ?? '—' }} ℃ / {{ item.humidity ?? '—' }} %</small></div><span class="status">{{ statusText[item.status] || item.status }}</span></div></section>
  </div>
</template>
<script>
import axios from 'axios'; import { API_BASE } from '@/config/api';
export default {data:()=>({harvests:[],items:[],showForm:false,busy:false,loading:false,loadError:'',message:'',stageText:{yellowing:'变黄',color_fixing:'定色',stem_drying:'干筋',complete:'已完成'},statusText:{planned:'待开始',running:'进行中',complete:'已完成',abnormal:'异常'},form:{batch_no:'',harvest_batch_id:'',barn_name:'',stage:'yellowing',temperature:'',humidity:''}}),mounted(){this.loadHarvests();this.load();},methods:{async loadHarvests(){try{const r=await axios.get(`${API_BASE}/harvest/batches/`);this.harvests=r.data.data?.items||[];}catch{this.harvests=[];}},async load(){this.loading=true;this.loadError='';try{const r=await axios.get(`${API_BASE}/curing/batches/`);this.items=r.data.data?.items||[];}catch(e){this.loadError=e.response?.data?.msg||'烘烤记录加载失败，请检查网络后重试。';}finally{this.loading=false;}},async create(){this.busy=true;this.message='';try{await axios.post(`${API_BASE}/curing/batches/`,this.form);this.message='烘烤批次已保存';this.showForm=false;await this.load();}catch(e){this.message=e.response?.data?.msg||'保存失败，请检查输入后重试。';}finally{this.busy=false;}}}};
</script>
<style scoped>
.workflow-page{max-width:1060px;margin:auto}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;padding:18px 2px}.eyebrow{font-size:12px;color:#27865a;font-weight:700}.page-head h1{margin:6px 0;color:#1b583c;font-size:26px}.page-head p{margin:0;color:#789081;font-size:13px}.primary,.secondary{border-radius:7px;padding:10px 15px;cursor:pointer;white-space:nowrap}.primary{border:0;background:#1f8758;color:#fff}.primary:disabled{opacity:.55;cursor:not-allowed}.secondary{border:1px solid #b8d7c4;background:#fff;color:#235c3d}.form-panel,.table-panel{background:#fff;border:1px solid #dcebe1;border-radius:8px;padding:17px;margin-bottom:14px}.form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}label{display:block;color:#41634f;font-size:12px;font-weight:600;margin-bottom:13px}input,select{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:10px;border:1px solid #cfe2d5;border-radius:7px;font:inherit;font-weight:400}.form-actions{display:flex;gap:8px}.panel-title{display:flex;justify-content:space-between;color:#285f43}.panel-title span,.batch-row small{color:#718b7b;font-size:12px}.empty{padding:35px 5px;text-align:center;color:#698171;font-size:13px}.empty p{margin:0 0 12px}.error{color:#a33b3b}.batch-row{display:flex;justify-content:space-between;align-items:center;gap:12px;border-top:1px solid #edf3ee;padding:13px 0}.batch-main{min-width:0}.batch-main strong{overflow-wrap:anywhere}.batch-row small{display:block;margin-top:4px}.status,.demo-tag{display:inline-block;padding:4px 8px;border-radius:5px;font-size:12px;white-space:nowrap}.status{background:#e8f5ed;color:#278258}.demo-tag{margin-left:8px;background:#fff1d6;color:#805208}.message,.form-hint{color:#2b8258;font-size:13px}@media(max-width:650px){.form-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:430px){.page-head{flex-direction:column}.page-head h1{font-size:22px}.page-head>.primary,.form-actions .primary,.form-actions .secondary{width:100%}.form-grid{grid-template-columns:1fr}.batch-row{align-items:flex-start;flex-direction:column}}
</style>
