<template>
  <div class="workflow-page">
    <header class="page-head"><div><span class="eyebrow">采叶 / 采收端</span><h1>采收批次</h1><p>记录地块、叶位与鲜重，形成可追溯的采收批次。</p></div><button class="primary" type="button" @click="showForm = !showForm">{{ showForm ? '收起表单' : '新建批次' }}</button></header>
    <form v-if="showForm" class="form-panel" @submit.prevent="create">
      <div class="form-grid"><label>批次号<input v-model.trim="form.batch_no" placeholder="如 2026-H-001" required></label><label>地块<select v-model="form.parcel_id" required><option value="">请选择地块</option><option v-for="p in parcels" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>采收日期<input v-model="form.harvest_date" type="date" required></label><label>鲜烟叶重量（kg）<input v-model="form.fresh_weight" type="number" min="0.01" step="0.01" required></label><label>叶位<input v-model.trim="form.leaf_position" placeholder="如中部叶、上部叶"></label><label>生育期<select v-model="form.growth_stage"><option>成熟期</option><option>旺长期</option></select></label></div>
      <label>备注<textarea v-model.trim="form.notes" rows="3" placeholder="可记录采收天气或现场情况"></textarea></label><div class="form-actions"><button class="primary" :disabled="busy || !parcels.length">{{ busy ? '保存中…' : '保存批次' }}</button><button class="secondary" type="button" @click="showForm=false">取消</button></div><p v-if="message" class="message" role="status">{{ message }}</p>
      <p v-if="!parcels.length" class="form-hint">当前没有可选地块，请先在种植端建立地块档案。</p>
    </form>
    <section class="table-panel"><div class="panel-title"><strong>批次记录</strong><span>{{ items.length }} 条</span></div><div v-if="loading" class="empty">正在加载批次…</div><div v-else-if="loadError" class="empty error"><p>{{ loadError }}</p><button class="secondary" @click="load">重试</button></div><div v-else-if="!items.length" class="empty">暂无采收批次。可以从现场采收记录开始建立档案。</div><div v-for="item in items" v-else :key="item.id" class="batch-row"><div class="batch-main"><strong>{{ item.batch_no }}</strong><span v-if="item.is_demo" class="demo-tag">演示样例</span><small>{{ item.parcel__name || '未命名地块' }} · {{ item.harvest_date }} · {{ item.fresh_weight }} kg</small></div><span class="status">{{ statusText[item.status] || item.status }}</span></div></section>
  </div>
</template>
<script>
import axios from 'axios'; import { API_BASE } from '@/config/api';
export default { data:()=>({ parcels:[],items:[],showForm:false,busy:false,loading:false,loadError:'',message:'',form:{batch_no:'',parcel_id:'',harvest_date:new Date().toISOString().slice(0,10),fresh_weight:'',leaf_position:'',growth_stage:'成熟期',notes:''},statusText:{pending:'待入库',stored:'已入库',sent_to_curing:'已送烘烤'} }),mounted(){this.loadParcels();this.load();},methods:{async loadParcels(){try{const uid=localStorage.getItem('userId');const r=await axios.get(`${API_BASE}/user/${uid}/fields/list/`);this.parcels=r.data.data||[];}catch{this.parcels=[];}},async load(){this.loading=true;this.loadError='';try{const r=await axios.get(`${API_BASE}/harvest/batches/`);this.items=r.data.data?.items||[];}catch(e){this.loadError=e.response?.data?.msg||'批次加载失败，请检查网络后重试。';}finally{this.loading=false;}},async create(){this.busy=true;this.message='';try{await axios.post(`${API_BASE}/harvest/batches/`,this.form);this.message='批次已保存';this.form.batch_no='';this.form.fresh_weight='';this.showForm=false;await this.load();}catch(e){this.message=e.response?.data?.msg||'保存失败，请检查输入后重试。';}finally{this.busy=false;}}} };
</script>
<style scoped>
.workflow-page{max-width:1060px;margin:auto}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;padding:18px 2px}.eyebrow{font-size:12px;color:#27865a;font-weight:700}.page-head h1{margin:6px 0;color:#1b583c;font-size:26px}.page-head p{margin:0;color:#789081;font-size:13px}.primary,.secondary{border-radius:7px;padding:10px 15px;cursor:pointer;white-space:nowrap}.primary{border:0;background:#1f8758;color:#fff}.primary:disabled{opacity:.55;cursor:not-allowed}.secondary{border:1px solid #b8d7c4;background:#fff;color:#235c3d}.form-panel,.table-panel{background:#fff;border:1px solid #dcebe1;border-radius:8px;padding:17px;margin-bottom:14px}.form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}label{display:block;color:#41634f;font-size:12px;font-weight:600;margin-bottom:13px}input,select,textarea{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:10px;border:1px solid #cfe2d5;border-radius:7px;font:inherit;font-weight:400}.form-actions{display:flex;gap:8px}.panel-title{display:flex;justify-content:space-between;color:#285f43}.panel-title span,.batch-row small{color:#718b7b;font-size:12px}.empty{padding:35px 5px;text-align:center;color:#698171;font-size:13px}.empty p{margin:0 0 12px}.error{color:#a33b3b}.batch-row{display:flex;justify-content:space-between;align-items:center;gap:12px;border-top:1px solid #edf3ee;padding:13px 0}.batch-main{min-width:0}.batch-main strong{overflow-wrap:anywhere}.batch-row small{display:block;margin-top:4px}.status,.demo-tag{display:inline-block;padding:4px 8px;border-radius:5px;font-size:12px;white-space:nowrap}.status{background:#e8f5ed;color:#278258}.demo-tag{margin-left:8px;background:#fff1d6;color:#805208}.message,.form-hint{color:#2b8258;font-size:13px}@media(max-width:650px){.form-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:430px){.page-head{flex-direction:column}.page-head h1{font-size:22px}.page-head>.primary,.form-actions .primary,.form-actions .secondary{width:100%}.form-grid{grid-template-columns:1fr}.batch-row{align-items:flex-start;flex-direction:column}}
</style>
