<template>
  <div class="workflow-page"><header class="page-head"><div><span class="eyebrow">收购 / 质检端</span><h1>质量检验</h1><p>关联采收批次，登记称重、含水率与复检状态。</p></div><button class="primary" type="button" @click="showForm=!showForm">{{ showForm ? '收起表单' : '新建质检' }}</button></header>
    <form v-if="showForm" class="form-panel" @submit.prevent="create"><div class="form-grid"><label>收购批次号<input v-model.trim="form.purchase_no" placeholder="如 2026-Q-001" required></label><label>采收批次<select v-model="form.harvest_batch_id" required><option value="">请选择采收批次</option><option v-for="b in harvests" :key="b.id" :value="b.id">{{ b.batch_no }} · {{ b.fresh_weight }} kg</option></select></label><label>称重（kg）<input v-model="form.weight" type="number" step="0.01" min="0.01" required></label><label>等级<input v-model.trim="form.grade" placeholder="现场定级后填写"></label><label>含水率（%）<input v-model="form.moisture" type="number" step="0.1" min="0" max="100"></label><label>状态<select v-model="form.status"><option value="pending">待质检</option><option value="passed">已通过</option><option value="recheck">需复检</option></select></label></div><label>外观与备注<textarea v-model.trim="form.notes" rows="3" placeholder="记录现场观察和复检原因"></textarea></label><div class="form-actions"><button class="primary" :disabled="busy || !harvests.length">{{ busy ? '保存中…' : '保存质检' }}</button><button class="secondary" type="button" @click="showForm=false">取消</button></div><p v-if="message" class="message" role="status">{{ message }}</p><p v-if="!harvests.length" class="form-hint">暂无可关联的采收批次，请先完成采收记录。</p></form>
    <section class="table-panel"><div class="panel-title"><strong>质检记录</strong><span>{{ items.length }} 条</span></div><div v-if="loading" class="empty">正在加载质检记录…</div><div v-else-if="loadError" class="empty error"><p>{{ loadError }}</p><button class="secondary" @click="load">重试</button></div><div v-else-if="!items.length" class="empty">暂无质检记录。等级与含水率需以现场实际测量为准。</div><div v-for="item in items" v-else :key="item.id" class="batch-row"><div class="batch-main"><strong>{{ item.purchase_no }}</strong><span v-if="item.is_demo" class="demo-tag">演示样例</span><small>{{ item.grade || '未定级' }} · {{ item.weight }} kg · 含水率 {{ item.moisture ?? '—' }} %</small></div><span class="status">{{ statusText[item.status] || item.status }}</span></div></section>
  </div>
</template>
<script>
import axios from 'axios'; import { API_BASE } from '@/config/api';
export default {data:()=>({harvests:[],items:[],showForm:false,busy:false,loading:false,loadError:'',message:'',statusText:{pending:'待质检',passed:'已通过',recheck:'需复检'},form:{purchase_no:'',harvest_batch_id:'',weight:'',grade:'',moisture:'',status:'pending',notes:''}}),mounted(){this.loadHarvests();this.load();},methods:{async loadHarvests(){try{const r=await axios.get(`${API_BASE}/harvest/batches/`);this.harvests=r.data.data?.items||[];}catch{this.harvests=[];}},async load(){this.loading=true;this.loadError='';try{const r=await axios.get(`${API_BASE}/quality/inspections/`);this.items=r.data.data?.items||[];}catch(e){this.loadError=e.response?.data?.msg||'质检记录加载失败，请检查网络后重试。';}finally{this.loading=false;}},async create(){this.busy=true;this.message='';try{await axios.post(`${API_BASE}/quality/inspections/`,this.form);this.message='质检记录已保存';this.showForm=false;await this.load();}catch(e){this.message=e.response?.data?.msg||'保存失败，请检查输入后重试。';}finally{this.busy=false;}}}};
</script>
<style scoped>
.workflow-page{max-width:1060px;margin:auto}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;padding:18px 2px}.eyebrow{font-size:12px;color:#27865a;font-weight:700}.page-head h1{margin:6px 0;color:#1b583c;font-size:26px}.page-head p{margin:0;color:#789081;font-size:13px}.primary,.secondary{border-radius:7px;padding:10px 15px;cursor:pointer;white-space:nowrap}.primary{border:0;background:#1f8758;color:#fff}.primary:disabled{opacity:.55;cursor:not-allowed}.secondary{border:1px solid #b8d7c4;background:#fff;color:#235c3d}.form-panel,.table-panel{background:#fff;border:1px solid #dcebe1;border-radius:8px;padding:17px;margin-bottom:14px}.form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}label{display:block;color:#41634f;font-size:12px;font-weight:600;margin-bottom:13px}input,select,textarea{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:10px;border:1px solid #cfe2d5;border-radius:7px;font:inherit;font-weight:400}.form-actions{display:flex;gap:8px}.panel-title{display:flex;justify-content:space-between;color:#285f43}.panel-title span,.batch-row small{color:#718b7b;font-size:12px}.empty{padding:35px 5px;text-align:center;color:#698171;font-size:13px}.empty p{margin:0 0 12px}.error{color:#a33b3b}.batch-row{display:flex;justify-content:space-between;align-items:center;gap:12px;border-top:1px solid #edf3ee;padding:13px 0}.batch-main{min-width:0}.batch-main strong{overflow-wrap:anywhere}.batch-row small{display:block;margin-top:4px}.status,.demo-tag{display:inline-block;padding:4px 8px;border-radius:5px;font-size:12px;white-space:nowrap}.status{background:#e8f5ed;color:#278258}.demo-tag{margin-left:8px;background:#fff1d6;color:#805208}.message,.form-hint{color:#2b8258;font-size:13px}@media(max-width:650px){.form-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:430px){.page-head{flex-direction:column}.page-head h1{font-size:22px}.page-head>.primary,.form-actions .primary,.form-actions .secondary{width:100%}.form-grid{grid-template-columns:1fr}.batch-row{align-items:flex-start;flex-direction:column}}
</style>
