<template>
  <div class="dashboard">
    <header class="page-head"><div><span class="eyebrow">{{ roleName }}工作台</span><h1>今日概览</h1></div><button class="switch" @click="$router.push('/workspaces')">切换角色</button></header>
    <p v-if="error" class="error" role="alert">{{ error }} <button @click="loadSummary">重试</button></p>
    <section class="metric-grid"><article v-for="metric in metrics" :key="metric.label"><span>{{ metric.label }}</span><strong>{{ metric.value }}</strong><small>{{ metric.hint }}</small></article></section>
    <section class="work-section"><h2>常用工作</h2><div class="action-grid"><button v-for="item in actions" :key="item.path" @click="$router.push(item.path)"><strong>{{ item.title }}</strong><span>{{ item.description }}</span><em>进入 →</em></button></div></section>
    <section v-if="recent.length" class="recent"><h2>最近批次</h2><div v-for="item in recent" :key="item.batch_no" class="recent-row"><strong>{{ item.batch_no }}</strong><span>{{ item.status }}</span></div></section>
    <p class="note">带“演示数据”标记的记录仅用于流程展示，现场结论以实际检测和登记为准。</p>
  </div>
</template>
<script>
import axios from 'axios';
import { API_BASE } from '@/config/api';
const roleNames={grower:'种植',plant_protection:'植保',harvest:'采收',curing:'烘烤',quality:'收购质检',admin:'管理'};
const actionsByRole={grower:[{title:'地块农情',description:'查看地块、天气与生育期',path:'/'},{title:'缺素识别',description:'上传叶片照片并查看提示',path:'/recognition'},{title:'施肥记录',description:'登记基肥和追肥作业',path:'/fertilization'},{title:'营养分析',description:'查看氮磷钾记录变化',path:'/analysis/deficiency'}],plant_protection:[{title:'病虫害识别',description:'上传照片并查看置信度',path:'/recognition'},{title:'农药记录',description:'登记防治作业',path:'/pesticide'},{title:'病害趋势',description:'按地块查看发生情况',path:'/analysis/disease'}],harvest:[{title:'采收批次',description:'记录叶位、鲜重与入库状态',path:'/harvest'}],curing:[{title:'烘烤批次',description:'记录烤房、阶段和温湿度',path:'/curing'}],quality:[{title:'质检记录',description:'称重、复检与批次追溯',path:'/quality'}],admin:[{title:'用户与角色',description:'分配工作角色和查看账号',path:'/admin'}]};
export default{data:()=>({metrics:[],recent:[],error:'',role:localStorage.getItem('activeRole')||''}),computed:{roleName(){return roleNames[this.role]||'生产'},actions(){return actionsByRole[this.role]||[]}},async mounted(){this.onRoleChange=()=>{this.role=localStorage.getItem('activeRole')||'';this.loadSummary()};window.addEventListener('role-change',this.onRoleChange);await this.loadSummary()},beforeUnmount(){window.removeEventListener('role-change',this.onRoleChange)},methods:{async loadSummary(){this.error='';try{const r=await axios.get(`${API_BASE}/workspace/summary/`);this.metrics=r.data?.data?.metrics||[];this.recent=r.data?.data?.recent||[]}catch(e){this.metrics=[];this.recent=[];this.error=e.response?.data?.msg||'工作台数据暂时无法加载'}}}};
</script>
<style scoped>
.dashboard{max-width:1160px;margin:auto;color:#203e2d}.page-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 0 20px;border-bottom:1px solid #dce8de}.eyebrow{color:#287b53;font-size:12px;font-weight:700}.page-head h1{margin:5px 0 0;font-size:25px}.switch{border:1px solid #bdd4c4;background:#fff;color:#1d704b;border-radius:6px;padding:9px 12px}.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:18px 0 25px}.metric-grid article{background:#fff;border:1px solid #dce8de;border-radius:7px;padding:16px;min-height:105px}.metric-grid span,.metric-grid small{display:block;color:#687f70;font-size:12px}.metric-grid strong{display:block;color:#174f37;font-size:27px;margin:9px 0 2px}.work-section h2,.recent h2{font-size:17px;margin:0 0 12px}.action-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.action-grid button{min-height:120px;display:flex;flex-direction:column;align-items:flex-start;gap:7px;text-align:left;border:1px solid #dce8de;border-radius:7px;background:#fff;color:#24513a;padding:15px}.action-grid span{font-size:12px;color:#71877a}.action-grid em{font-style:normal;font-size:12px;color:#22835a;margin-top:auto}.recent{margin-top:26px}.recent-row{display:flex;justify-content:space-between;padding:11px 4px;border-bottom:1px solid #e2ebe4;font-size:13px}.recent-row span{color:#708477}.note{font-size:12px;color:#7c8c80;margin-top:24px}.error{padding:11px;background:#fff5e8;color:#835723;border-radius:6px}.error button{border:0;background:transparent;color:#815011;text-decoration:underline}@media(max-width:700px){.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.action-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.metric-grid,.action-grid{grid-template-columns:1fr}}
</style>
