<template>
  <div class="dashboard" :class="`role-${role || 'unknown'}`">
    <header class="page-head"><div><span class="eyebrow">{{ roleName }}工作台</span><h1>{{ roleHeadline }}</h1><p class="role-intro">{{ roleIntro }}</p></div><button class="switch" @click="$router.push('/workspaces')">切换角色</button></header>
    <p v-if="error" class="error" role="alert">{{ error }} <button @click="loadSummary">重试</button></p>
    <section class="metric-grid" :aria-label="`${roleName}关键指标`"><article v-for="metric in metrics" :key="metric.label"><span>{{ metric.label }}</span><strong>{{ metric.value }}</strong><small>{{ metric.hint }}</small></article></section>
    <div class="work-layout">
      <section class="work-section"><div class="section-heading"><h2>{{ actionTitle }}</h2><span>{{ actions.length }} 个入口</span></div><div class="action-grid"><button v-for="item in actions" :key="item.path" @click="$router.push(item.path)"><strong>{{ item.title }}</strong><span>{{ item.description }}</span><em>进入 →</em></button></div></section>
      <section class="recent"><div class="section-heading"><h2>{{ recentTitle }}</h2><span v-if="recent.length">{{ recent.length }} 条</span></div><div v-if="recent.length" class="recent-list"><div v-for="(item, index) in recent" :key="index" class="recent-row"><strong>{{ item.label }} <small v-if="item.is_demo">演示数据</small></strong><span>{{ item.status_label }}</span></div></div><p v-else class="recent-empty">{{ recentEmptyText }}</p></section>
    </div>
    <p class="note">带“演示数据”标记的记录仅用于流程展示，现场结论以实际检测和登记为准。</p>
  </div>
</template>
<script>
import axios from 'axios';
import { API_BASE } from '@/config/api';
const roleNames={grower:'种植',plant_protection:'植保',harvest:'采收',curing:'烘烤',quality:'收购质检',admin:'管理'};
const roleCopy={grower:['种植作业总览','查看地块健康、天气和营养记录'],plant_protection:['病虫害防控总览','关注识别复核、防治任务与用药记录'],harvest:['采收进度总览','跟踪采收批次、鲜重和送烘烤状态'],curing:['烘烤过程总览','跟踪烤房阶段、温湿度和异常事项'],quality:['收购质检总览','处理待检批次、等级和来源追溯'],admin:['生产运营总览','查看用户、角色和全局业务运行状态']};
const actionsByRole={grower:[{title:'地块农情',description:'地块、天气与生育期',path:'/'},{title:'缺素识别',description:'叶片识别与复核',path:'/recognition'},{title:'施肥记录',description:'基肥与追肥作业',path:'/fertilization'},{title:'营养分析',description:'氮磷钾记录趋势',path:'/analysis/deficiency'}],plant_protection:[{title:'病虫害识别',description:'叶片照片与识别结果',path:'/recognition'},{title:'农药记录',description:'施药与防治对象',path:'/pesticide'},{title:'病害趋势',description:'按地块查看发生情况',path:'/analysis/disease'}],harvest:[{title:'采收批次',description:'叶位、鲜重与入库状态',path:'/harvest'},{title:'AI 作业助手',description:'采收与入库问题咨询',path:'/ai'}],curing:[{title:'烘烤批次',description:'烤房、阶段与温湿度',path:'/curing'},{title:'AI 作业助手',description:'烘烤阶段问题咨询',path:'/ai'}],quality:[{title:'质检记录',description:'称重、复检与来源追溯',path:'/quality'},{title:'AI 作业助手',description:'分级与复检问题咨询',path:'/ai'}],admin:[{title:'用户与角色',description:'账号与岗位权限',path:'/admin'},{title:'AI 作业助手',description:'业务问题咨询',path:'/ai'}]};
const sectionsByRole={grower:['种植工作','最近施肥记录','暂无施肥记录'],plant_protection:['防治工作','最近防治记录','暂无防治记录'],harvest:['采收作业','最近采收批次','暂无采收批次'],curing:['烤房作业','最近烘烤批次','暂无烘烤批次'],quality:['质检作业','最近质检记录','暂无质检记录'],admin:['权限管理','最近采收批次','暂无采收批次']};
export default{data:()=>({metrics:[],recent:[],error:'',role:localStorage.getItem('activeRole')||JSON.parse(localStorage.getItem('roles')||'[]')[0]?.code||''}),computed:{roleName(){return roleNames[this.role]||'生产'},roleHeadline(){return roleCopy[this.role]?.[0]||'生产工作台'},roleIntro(){return roleCopy[this.role]?.[1]||'查看当前岗位的业务信息'},actionTitle(){return sectionsByRole[this.role]?.[0]||'当前工作'},recentTitle(){return sectionsByRole[this.role]?.[1]||'最近记录'},recentEmptyText(){return sectionsByRole[this.role]?.[2]||'暂无记录'},actions(){return actionsByRole[this.role]||[]}},async mounted(){this.onRoleChange=()=>{this.role=localStorage.getItem('activeRole')||'';this.loadSummary()};window.addEventListener('role-change',this.onRoleChange);await this.loadSummary()},beforeUnmount(){window.removeEventListener('role-change',this.onRoleChange)},methods:{async loadSummary(){this.error='';try{const r=await axios.get(`${API_BASE}/workspace/summary/`);this.role=r.data?.data?.role||this.role;this.metrics=r.data?.data?.metrics||[];this.recent=r.data?.data?.recent||[]}catch(e){this.metrics=[];this.recent=[];if(e.response?.status!==401)this.error=e.response?.data?.msg||'工作台数据暂时无法加载，请检查网络后重试'}}}};
</script>
<style scoped>
.dashboard{max-width:1160px;margin:auto;color:#203e2d}.page-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 0 20px;border-bottom:1px solid #dce8de}.eyebrow{color:#287b53;font-size:12px;font-weight:700}.page-head h1{margin:5px 0 0;font-size:25px}.role-intro{margin:6px 0 0;color:#718277;font-size:13px}.switch{border:1px solid #bdd4c4;background:#fff;color:#1d704b;border-radius:6px;padding:9px 12px}.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:18px 0 25px}.metric-grid article{background:#fff;border:1px solid #dce8de;border-radius:7px;padding:16px;min-height:105px}.metric-grid span,.metric-grid small{display:block;color:#687f70;font-size:12px}.metric-grid strong{display:block;color:#174f37;font-size:27px;margin:9px 0 2px}.work-section h2,.recent h2{font-size:17px;margin:0 0 12px}.action-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.action-grid button{min-height:120px;display:flex;flex-direction:column;align-items:flex-start;gap:7px;text-align:left;border:1px solid #dce8de;border-radius:7px;background:#fff;color:#24513a;padding:15px}.action-grid span{font-size:12px;color:#71877a}.action-grid em{font-style:normal;font-size:12px;color:#22835a;margin-top:auto}.recent{margin-top:26px}.recent-row{display:flex;justify-content:space-between;padding:11px 4px;border-bottom:1px solid #e2ebe4;font-size:13px}.recent-row span{color:#708477}.note{font-size:12px;color:#7c8c80;margin-top:24px}.error{padding:11px;background:#fff5e8;color:#835723;border-radius:6px}.error button{border:0;background:transparent;color:#815011;text-decoration:underline}@media(max-width:700px){.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.action-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.metric-grid,.action-grid{grid-template-columns:1fr}}
.dashboard{--role-accent:#267a50;--role-soft:#edf6ef;--role-line:#c9dfce}.role-harvest{--role-accent:#8b642f;--role-soft:#f7f1e7;--role-line:#e7d7b9}.role-curing{--role-accent:#a44f3e;--role-soft:#fbefeb;--role-line:#edcfc5}.role-quality{--role-accent:#366f7e;--role-soft:#eaf4f6;--role-line:#c6dfe4}.role-admin{--role-accent:#536a60;--role-soft:#edf1ef;--role-line:#d2dfd7}.role-plant_protection{--role-accent:#6d7935;--role-soft:#f2f5e8;--role-line:#dbe4c2}
.dashboard .eyebrow,.dashboard .metric-grid strong,.dashboard .action-grid em{color:var(--role-accent)}.dashboard .page-head{border-bottom-color:var(--role-line)}.dashboard .switch{color:var(--role-accent);border-color:var(--role-line)}.dashboard .metric-grid{margin:18px 0 24px}.dashboard .metric-grid article{border-radius:6px;min-height:104px;padding:15px 17px}.dashboard .metric-grid article:first-child{background:var(--role-soft);border-color:var(--role-line)}
.work-layout{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(300px,.9fr);gap:28px;align-items:start}.section-heading{display:flex;align-items:baseline;justify-content:space-between;gap:12px;border-bottom:1px solid #dce8de;padding-bottom:9px;margin-bottom:12px}.section-heading h2{margin:0;font-size:16px}.section-heading>span{color:#809285;font-size:12px;white-space:nowrap}.dashboard .action-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.dashboard .action-grid button{min-height:95px;border-radius:6px;padding:13px}.dashboard .action-grid button:first-child{border-color:var(--role-line)}.dashboard .action-grid button:hover{border-color:var(--role-accent);background:var(--role-soft)}.dashboard .action-grid strong{font-size:14px}.dashboard .action-grid span{line-height:1.45}.dashboard .recent{margin:0}.recent-list{background:#fff;border:1px solid #dce8de;border-radius:6px;padding:0 14px}.dashboard .recent-row{align-items:center;gap:14px;min-height:45px;padding:9px 0}.dashboard .recent-row:last-child{border-bottom:0}.dashboard .recent-row strong{min-width:0;overflow-wrap:anywhere}.dashboard .recent-row span{flex:none;text-align:right}.recent-row small{display:inline-block;margin-left:5px;font-size:10px;font-weight:400;color:#8a642f}.recent-empty{margin:0;border:1px dashed var(--role-line);border-radius:6px;background:var(--role-soft);padding:28px 16px;color:#6e8073;font-size:13px;text-align:center}.dashboard .note{margin-top:18px}
@media(max-width:850px){.work-layout{grid-template-columns:1fr;gap:22px}.dashboard .action-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.dashboard .page-head{align-items:flex-start}.dashboard .page-head h1{font-size:22px}.dashboard .switch{font-size:12px;padding:7px 9px;white-space:nowrap}.dashboard .metric-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.dashboard .metric-grid article{padding:11px 9px;min-height:96px}.dashboard .metric-grid strong{font-size:22px}.dashboard .metric-grid span,.dashboard .metric-grid small{font-size:11px;line-height:1.4}.dashboard .action-grid{grid-template-columns:1fr}.dashboard .action-grid button{min-height:78px}.dashboard .recent-row{align-items:flex-start}.dashboard .recent-row span{max-width:40%;overflow-wrap:anywhere}}
</style>
