<template>
  <div class="nav-shell"><header class="top-bar"><div class="brand"><img :src="brandLogo" class="logo"><span class="title">叶擎慧航</span><span class="role-label">{{ activeRoleName }}</span></div><div class="user-actions"><select v-if="roles.length > 1" v-model="activeRole" @change="switchRole"><option v-for="role in roles" :key="role.code" :value="role.code">{{ role.name }}</option></select><span>{{ username || '用户' }}</span><button @click="logout">退出</button></div></header><nav class="bottom-tab"><button v-for="item in navItems" :key="item.path + item.title" @click="goToPage(item.path)" :class="{active:isCurrentPath(item.path)}"><img :src="item.icon" class="tab-icon"><span>{{ item.title }}</span></button></nav></div>
</template>
<script>
import brandLogo from '@/assets/icons/brand-logo.png'; import homeIcon from '@/assets/icons/home-icon.png'; import fertilizationIcon from '@/assets/icons/fertilization-icon.png'; import deviceIcon from '@/assets/icons/device-icon.png'; import aiIcon from '@/assets/icons/ai-icon.png'; import strategyIcon from '@/assets/icons/strategy-icon.png'; import searchIcon from '@/assets/icons/search-icon.png';
const roleNames={grower:'种植端',plant_protection:'植保端',harvest:'采收端',curing:'烘烤端',quality:'质检端',admin:'管理员端'};
export default {data(){return {brandLogo,username:localStorage.getItem('username')||'',roles:JSON.parse(localStorage.getItem('roles')||'[]'),activeRole:localStorage.getItem('activeRole')||'',allNavItems:[
{path:'/',icon:homeIcon,title:'首页',roles:['grower']},{path:'/workspace-dashboard',icon:homeIcon,title:'工作台',roles:['plant_protection','harvest','curing','quality','admin']},{path:'/recognition',icon:searchIcon,title:'缺素识别',roles:['grower']},{path:'/fertilization',icon:fertilizationIcon,title:'施肥作业',roles:['grower']},{path:'/strategy',icon:strategyIcon,title:'生育期策略',roles:['grower']},{path:'/analysis',icon:strategyIcon,title:'数据分析',roles:['grower']},
{path:'/recognition',icon:searchIcon,title:'病虫识别',roles:['plant_protection']},{path:'/pesticide',icon:fertilizationIcon,title:'农药记录',roles:['plant_protection']},{path:'/analysis/disease',icon:strategyIcon,title:'发生趋势',roles:['plant_protection']},{path:'/device',icon:deviceIcon,title:'植保设备',roles:['plant_protection']},{path:'/harvest',icon:searchIcon,title:'采收批次',roles:['harvest']},{path:'/curing',icon:deviceIcon,title:'烘烤批次',roles:['curing']},{path:'/quality',icon:strategyIcon,title:'质量检验',roles:['quality']},{path:'/admin',icon:deviceIcon,title:'用户与角色',roles:['admin']},{path:'/ai',icon:aiIcon,title:'AI 助手',roles:['grower','plant_protection','harvest','curing','quality','admin']}]};},computed:{navItems(){const active=this.activeRole||this.roles[0]?.code;return this.allNavItems.filter(item=>item.roles.includes(active)).slice(0,5);},activeRoleName(){return roleNames[this.activeRole]||'工作台';}},mounted(){this.onRoleChange=e=>{this.activeRole=e.detail;};window.addEventListener('role-change',this.onRoleChange);},beforeUnmount(){window.removeEventListener('role-change',this.onRoleChange);},methods:{switchRole(){localStorage.setItem('activeRole',this.activeRole);window.dispatchEvent(new CustomEvent('role-change',{detail:this.activeRole}));this.$router.push(['grower','plant_protection'].includes(this.activeRole)?'/':'/workspace-dashboard');},goToPage(path){if(this.$route.path!==path)this.$router.push(path);},isCurrentPath(path){return path==='/'?this.$route.path==='/':path==='/fertilization'?(this.$route.path==='/fertilization'||this.$route.path==='/pesticide'):this.$route.path===path;},logout(){['token','userId','username','roles','activeRole'].forEach(k=>localStorage.removeItem(k));this.$router.push('/login');}}};
</script>
<style scoped>
.top-bar{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;background:linear-gradient(100deg,#1d8f62,#2cb478);position:fixed;top:0;left:0;right:0;z-index:100;color:#fff}.brand,.user-actions{display:flex;align-items:center;gap:8px}.logo{width:32px;height:32px}.title{font-size:17px;font-weight:700}.role-label{font-size:11px;opacity:.8}select,button{font:inherit}select{max-width:110px;background:#fff;color:#234d38;border-radius:6px;padding:4px}.user-actions button{border:1px solid rgba(255,255,255,.4);background:transparent;color:#fff;border-radius:6px;padding:5px 10px}.bottom-tab{position:fixed;left:0;right:0;bottom:0;min-height:56px;padding:6px;background:#fff;display:grid;grid-template-columns:repeat(5,1fr);gap:4px;border-top:1px solid #dfebe3;z-index:1000}.bottom-tab button{border:0;background:transparent;border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;color:#6d8578;font-size:10px}.bottom-tab button.active{background:#e9f7ef;color:#1f8758;font-weight:700}.tab-icon{width:19px;height:19px}@media(min-width:980px){.bottom-tab{max-width:740px;left:50%;right:auto;width:740px;transform:translateX(-50%);border-radius:14px 14px 0 0}}
.top-bar{height:var(--header-h);padding:0 14px;background:var(--color-primary)}
.bottom-tab{border-color:var(--color-border);box-shadow:var(--shadow-soft)}
.bottom-tab button.active{background:#e9f2eb;color:var(--color-primary)}
.top-bar{display:flex;gap:8px;background:#1f6f4a}.brand,.user-actions{min-width:0;white-space:nowrap}.brand{flex:1}.title{font-size:16px;font-weight:600}.user-actions{flex:none}.user-actions>span{max-width:90px;overflow:hidden;text-overflow:ellipsis}.user-actions button{white-space:nowrap}
.bottom-tab{max-width:none;width:auto;left:0;right:0;transform:none;border-radius:0;min-height:64px;grid-template-columns:none;grid-auto-flow:column;grid-auto-columns:minmax(0,1fr);padding-bottom:calc(6px + env(safe-area-inset-bottom,0px))}
.bottom-tab button{border-radius:6px;min-width:0;white-space:nowrap;font-size:11px}
@media(max-width:520px){.title{font-size:14px}.role-label{font-size:11px}.brand,.user-actions{gap:5px}.user-actions>span{display:none}.user-actions select{max-width:82px;font-size:12px}.user-actions button{padding:5px 6px;font-size:12px}}
@media(min-width:1024px){.bottom-tab{top:var(--header-h);bottom:0;right:auto;width:196px;min-height:0;padding:16px 8px;display:flex;flex-direction:column;gap:4px;border-top:0;border-right:1px solid var(--color-border)}.bottom-tab button{width:100%;min-height:42px;flex-direction:row;justify-content:flex-start;gap:12px;padding:0 12px;font-size:13px}}
</style>
